import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";
import { imageBank, plantart, realWorkImages } from "../lib/plantart";
import { BreadcrumbJsonLd, pageMetadata } from "../lib/seo";

export const metadata: Metadata = pageMetadata({ title: "Paisagismo em Brasília", description: "Paisagismo da Plantart em Brasília/DF: jardins, áreas externas, vegetação e natureza integrada à arquitetura.", path: "/paisagismo", image: "/trabalhos/paisagismo-piscina-palmeiras-plantart-tratada.webp" });
const steps = [["01", "Conversar", "Entender o espaço, a rotina e o que você deseja transformar."], ["02", "Planejar", "Organizar espécies, materiais e composição para o ambiente."], ["03", "Transformar", "Dar forma ao jardim e integrar natureza e arquitetura."], ["04", "Acompanhar", "Orientar os próximos cuidados para manter o espaço vivo."]];

const serviceJsonLd = { "@context": "https://schema.org", "@type": "Service", name: "Paisagismo Plantart", serviceType: "Paisagismo", provider: { "@id": `${plantart.officialUrl}/#organization` }, areaServed: { "@type": "City", name: "Brasília" }, url: `${plantart.officialUrl}/paisagismo`, description: "Serviço de paisagismo da Plantart para jardins e áreas externas em Brasília/DF." };

export default function PaisagismoPage() { return <main><section className="hero inner-hero"><Image src={imageBank.landscapeHero} alt="Paisagismo residencial com piscina e palmeiras" fill priority sizes="100vw" /><div className="hero-shade" /><div className="hero-content container"><p className="eyebrow">Paisagismo em Brasília</p><h1>Natureza pensada para o seu espaço.</h1><p className="hero-lead">Jardins, áreas externas e composições que aproximam a arquitetura da natureza.</p><a className="btn btn--light" href={plantart.whatsappLandscapeUrl} target="_blank" rel="noreferrer">Solicitar orçamento</a></div></section><section className="section manifesto container"><p className="eyebrow">Como ajudamos</p><h2>Mais do que decorar: criar espaços para viver melhor.</h2><p>O paisagismo da Plantart considera vegetação, luz, circulação, materiais e a relação do ambiente com a rotina de quem vai usá-lo. Para projetos em Taguatinga ou outras regiões do Distrito Federal, confirme previamente a disponibilidade de atendimento pelo WhatsApp.</p></section><section className="section steps-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">Nosso processo</p><h2>Do primeiro contato ao jardim.</h2></div><p>Um caminho simples para tirar o projeto do papel.</p></div><div className="steps-grid">{steps.map(([number, title, text]) => <article key={number}><strong>{number}</strong><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><section className="section real-work-section container"><div className="section-heading"><div><p className="eyebrow">Registros reais</p><h2>Conheça alguns trabalhos da Plantart.</h2></div><Link className="arrow-link" href="/nossos-trabalhos">Ver portfólio →</Link></div><div className="work-preview">{realWorkImages.map((item) => <Link href="/nossos-trabalhos" className="work-preview-card" key={item.src}><Image src={item.src} alt={item.alt} fill sizes="(max-width: 700px) 100vw, 50vw" /><span>{item.title}</span></Link>)}</div></section><section className="landscape-cta container"><p className="eyebrow">Vamos conversar?</p><h2>Conte o que você deseja transformar.</h2><p>Envie uma mensagem pelo WhatsApp para solicitar informações sobre paisagismo.</p><a className="btn btn--primary" href={plantart.whatsappLandscapeUrl} target="_blank" rel="noreferrer">Solicitar orçamento</a></section><BreadcrumbJsonLd items={[{ name: "Início", path: "/" }, { name: "Paisagismo", path: "/paisagismo" }]} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(serviceJsonLd) }} /></main>; }
