import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";
import { MapBlock, VisitCta } from "./components/SiteChrome";
import { imageBank, plantart, productCategories, realWorkImages } from "./lib/plantart";
import { pageMetadata } from "./lib/seo";

export const metadata: Metadata = pageMetadata({ title: "Floricultura, plantas e paisagismo em Brasília", description: "Floricultura e Garden Center em Vicente Pires, Brasília/DF, com plantas, flores, vasos, materiais de jardinagem e atendimento para paisagismo.", path: "/" });

export default function Home() {
  return <main>
    <section className="hero hero-home"><Image src={imageBank.heroGarden} alt="Garden Center Plantart com plantas, vasos e flores ao ar livre" fill priority sizes="100vw" /><div className="hero-shade" /><div className="hero-content container"><p className="eyebrow">Garden Center & Paisagismo em Brasília</p><h1>Plantas, flores e paisagismo para transformar seus ambientes.</h1><p className="hero-lead">Encontre espécies, materiais de jardinagem e soluções paisagísticas para deixar sua casa, empresa ou área externa mais viva.</p><div className="button-row"><Link className="btn btn--primary" href="/garden-center">Conheça nossos produtos</Link><a className="btn btn--light" href={plantart.whatsappGeneralUrl} target="_blank" rel="noreferrer">Fale pelo WhatsApp</a></div><div className="hero-proof"><span>24+ anos de atuação</span><span>Vicente Pires · Brasília</span></div></div></section>
    <section className="section intro-section container"><div><p className="eyebrow">Tudo para cultivar</p><h2>Um Garden Center para escolher com calma e orientação.</h2></div><div><p>A Plantart reúne plantas ornamentais, flores, mudas, vasos, terras, substratos, adubos e outros materiais para jardinagem.</p><Link className="arrow-link" href="/garden-center">Ver Garden Center <span>→</span></Link></div></section>
    <section className="section category-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">Encontre por categoria</p><h2>O que você procura?</h2></div><Link className="arrow-link" href="/garden-center">Todas as categorias →</Link></div><div className="category-grid">{productCategories.slice(0, 6).map((item) => <Link className="category-card" href="/garden-center" key={item.name}><div className="category-image"><Image src={item.image} alt="" fill sizes="(max-width: 700px) 100vw, 33vw" /></div><div><h3>{item.name}</h3><p>{item.description}</p><span>Consultar disponibilidade →</span></div></Link>)}</div></div></section>
    <section className="feature-split container"><div className="feature-image"><Image src={imageBank.landscapeHero} alt="Paisagismo residencial com piscina e palmeiras realizado pela Plantart" fill sizes="(max-width: 900px) 100vw, 50vw" /></div><div className="feature-copy"><p className="eyebrow">Paisagismo</p><h2>Seu espaço pode respirar melhor.</h2><p>Projetos de paisagismo conectam vegetação, materiais e arquitetura para criar áreas externas mais acolhedoras e funcionais.</p><Link className="btn btn--primary" href="/paisagismo">Conheça o paisagismo</Link></div></section>
    <section className="section works-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">Nossos trabalhos</p><h2>Projetos que já ganharam vida.</h2></div><Link className="arrow-link" href="/nossos-trabalhos">Ver galeria completa →</Link></div><div className="work-preview">{realWorkImages.map((item) => <Link href="/nossos-trabalhos" className="work-preview-card" key={item.src}><Image src={item.src} alt={item.alt} fill sizes="(max-width: 700px) 100vw, 50vw" /><span>{item.title}</span></Link>)}</div></div></section>
    <section className="reasons-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">Por que Plantart?</p><h2>Experiência para ajudar você a escolher melhor.</h2></div></div><div className="reason-grid"><article><strong>01</strong><h3>Escolha presencial</h3><p>Veja espécies, tamanhos, vasos e composições de perto.</p></article><article><strong>02</strong><h3>Jardinagem completa</h3><p>Encontre materiais para plantar, cuidar e manter seu jardim.</p></article><article><strong>03</strong><h3>Paisagismo</h3><p>Conte com uma frente dedicada a transformar áreas externas.</p></article></div></div></section>
    <VisitCta />
    <section className="section location-section container"><div className="location-copy"><p className="eyebrow">Onde estamos</p><h2>Venha visitar a Plantart.</h2><p>{plantart.addressLine1}<br />{plantart.addressLine2}<br />{plantart.addressLine3} · {plantart.cep}</p><p>A loja fica em Vicente Pires, Brasília/DF. Para quem pesquisa por floricultura ou Garden Center na região de Taguatinga, consulte a rota e confirme o melhor caminho até a loja.</p><p><strong>Horários</strong><br />Seg–Sex 08h–18h · Sáb 09h–18h · Dom 09h–13h</p><p><strong>Telefone e WhatsApp</strong><br /><a className="arrow-link" href={`tel:${plantart.telephoneE164}`}>{plantart.whatsappLabel} →</a></p><a className="btn btn--primary" href={plantart.mapsUrl} target="_blank" rel="noreferrer">Como chegar</a></div><MapBlock /></section>
  </main>;
}
