import Image from "next/image";
import type { Metadata } from "next";
import { ContactForm } from "../components/ContactForm";
import { MapBlock } from "../components/SiteChrome";
import { imageBank, plantart } from "../lib/plantart";
import { BreadcrumbJsonLd, pageMetadata } from "../lib/seo";

export const metadata: Metadata = pageMetadata({ title: "Contato e localização", description: "Endereço, horários, telefone, WhatsApp, mapa e localização da Floricultura Plantart em Vicente Pires, Brasília/DF.", path: "/contato" });

export default function ContatoPage() {
  return <main><section className="contact-hero"><div><p className="eyebrow">Fale com a Plantart</p><h1>Venha visitar, perguntar e começar seu próximo projeto.</h1><p>Estamos em Vicente Pires, Brasília/DF. Para consultar produtos ou solicitar um orçamento de paisagismo, fale conosco pelo WhatsApp.</p></div><Image src={imageBank.greenhouse} alt="Fachada da Floricultura Plantart, com placa da loja e plantas expostas na entrada" width={1734} height={907} priority sizes="(max-width: 760px) 100vw, 50vw" /></section><section className="contact-grid"><div className="contact-card primary"><p className="eyebrow">Visite a loja</p><h2>{plantart.addressLine1}</h2><address>{plantart.addressLine2}<br />{plantart.addressLine3}<br />{plantart.cep}</address><a className="btn btn--light" href={plantart.mapsUrl} target="_blank" rel="noreferrer">Como chegar</a><a className="btn btn--ghost contact-card__whatsapp" href={plantart.whatsappGeneralUrl} target="_blank" rel="noreferrer">Falar pelo WhatsApp</a></div><div className="contact-card"><p className="eyebrow">Horário de funcionamento</p><ul className="hours-list">{plantart.hours.map(([day, hour]) => <li key={day}><span>{day}</span><strong>{hour}</strong></li>)}</ul></div><div className="contact-card"><p className="eyebrow">Canais oficiais</p><a className="arrow-link" href={`tel:${plantart.telephoneE164}`}>Ligar: {plantart.whatsappLabel} →</a><a className="arrow-link" href={plantart.whatsappGeneralUrl} target="_blank" rel="noreferrer">WhatsApp →</a><a className="arrow-link" href={plantart.instagramUrl} target="_blank" rel="noreferrer">{plantart.instagram} →</a></div><div className="contact-card"><p className="eyebrow">Mensagem rápida</p><ContactForm /></div></section><section className="map-section"><MapBlock /></section><BreadcrumbJsonLd items={[{ name: "Início", path: "/" }, { name: "Contato", path: "/contato" }]} /></main>;
}
